version: '3.3'
services:
  database:
    image: postgres:13
    environment:
    - POSTGRES_DB=task_db
    - POSTGRES_USER=maldonado
    - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
    volumes:
    - ./task_db:/var/lib/postgresql/data
